spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/plac
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver
  jpa:
    ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  format_sql: true
logging.level:
  org.hibernate.SQL: debug