datasource:
  url: jdbc:mysql://localhost:3306/plac?useSSL=false&serverTimezone=UTC
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password:
  hikari:
    connection-test-query: select 1
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

#logging:
#  level:
#    org.hibernate: DEBUG
#    org.springframework: DEBUG